sudo: required

language: node_js
    
services:
    - docker

script:
    - docker run -e CI=true ariadnarouco/react-front npm run test

before_install:
    - docker build -t ariadnarouco/react-front -f Dockerfile.dev .
