sudo: required

language: node_js

services:
    - docker

before_install:
    - docker build -t ariadnarouco/react-front -f Dockerfile.dev .

script:
    - docker run -e CI=true ariadnarouco/react-front npm run test
